app/models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('posts.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'))
)




class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    content = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {},  name: {}>'.format(self.id, self.name)



roles_users = db.Table('roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('roles.id'))
)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField



class PostForm(Form):
    title = StringField('Title')
    tag = StringField('Tag')
    content = TextAreaField('Content')

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask import redirect, url_for, request

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)



from models import *

class AdminView(ModelView):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, **kwargs):
        return redirect(url_for('security.login', next=request.url ))

class HomeAdminView(AdminIndexView):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url ))

admin = Admin(app, 'Flaskapp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(AdminView(Tag, db.session))
admin.add_view(AdminView(Post, db.session))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/main.py
from app import app
from app import db

import views



if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

from models import Post, Tag
from app import db
from .forms import PostForm

from flask_security import login_required

import re


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        tag_names = re.sub(r'\s+','',request.form['tag']).split(',')

        try:
            post = Post(title=title, content=content)
            for tag_name in tag_names:
                if not Tag.query.filter(Tag.name == tag_name).first():
                    tag = Tag(name=tag_name)
                else:
                    tag = Tag.query.filter(Tag.name == tag_name).first()
                post.tags.append(tag)
            db.session.add(post)
            db.session.commit()
        except Exception as e:
            print('exception', e)

        return redirect( url_for('posts.index') )
    form = PostForm()
    return render_template('posts/create_post.html', form=form)

@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect (url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    posts = Post.query.all()
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.content.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=10)

    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts
    return render_template('posts/tag_detail.html', posts=posts, tag=tag)

@posts.route('/tags')
def tags():
    tags = Tag.query.all()
    return render_template('posts/tags.html', tags=tags)

app/views.py
from app import app
from flask import render_template
from posts.blueprint import posts


app.register_blueprint(posts, url_prefix='/blog')

@app.route('/')
def index():
    return render_template('index.html')

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
  Create Post
{% endblock %}


{% block content_title %}
  New Post
{% endblock %}

{% block content %}

    <form class="" action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form %}
          <div class="form-group">
              {{ field.label(class='control-label') }}
              {{ field(class='form-control') }}
          </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Create">
    </form>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}


{% block title %}
  Edit Post
{% endblock %}


{% block content_title %}
  Edit Post: "{{ post.title }}"
{% endblock %}

{% block content %}

    <form class="" action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {% for field in form %}
          {% if field.name != 'tag' %}
          <div class="form-group">
              {{ field.label(class='control-label') }}
              {{ field(class='form-control') }}
          </div>
          {% endif %}
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="edit">
    </form>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}
  blog
{% endblock %}


{% block content_title %}
  Posts
{% endblock %}

{% block content %}

{% for post in pages.items %}
  <p>
    <a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</a>
    {% for tag in post.tags %}
      <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
        <span class="badge badge-success">{{ tag.name }}</span>
      </a>
    {% endfor %}
  </p>
{% endfor %}

<nav aria-label="...">
  <ul class="pagination">
    <li
    {% if pages.has_prev %}
    class="page-item">
    {% else %}
    class="page-item disabled">
    {% endif %}
    <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% for page in pages.iter_pages() %}
      <li {% if pages.page==page %} class="page-item active" {% else %} class="page-item" {% endif %} >
        <a class="page-link" href="./?page={{page}}">{{page}}</a></li>
    {% endfor %}



    <li  {% if pages.has_next %}
    class="page-item"
    {% else %}
    class="page-item disabled"
    {% endif %}class="page-item">
      <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
    </li>
  </ul>
</nav>

{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block title %}
  {{ post.title }}
{% endblock %}


{% block content_title %}

  {{ post.title }}

{% endblock %}

{% block content %}

  {{ post.content }}
  <div class="tags">
    {% for tag in tags %}
      <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-success">{{ tag.name }}</span></a>

    {% endfor %}
  </div>
  <a href="{{ url_for('posts.edit_post', slug=post.slug)}}">edit</a>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}


{% block title %}
  {{ tag.name }}
{% endblock %}


{% block content_title %}

  {{ tag.name }}

{% endblock %}

{% block content %}


  <div class="col">
    {% for post in posts %}
    <div class="">


      <a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/posts/templates/posts/tags.html
{% extends 'base.html' %}


{% block title %}
  tags
{% endblock %}


{% block content_title %}
  Tags
{% endblock %}

{% block content %}

  {% for tag in tags %}
      <p>
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a>

      </p>
  {% endfor %}

{% endblock %}

app/templates/base.html
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <meta charset="utf-8">
    <title>

      {% block title %}

      {% endblock %} | Flask app

    </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('posts.tags') }}">Tags</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('posts.create_post') }}" tabindex="-1">Create</a>
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

      </div>
    </nav>

    <div class="container">
      <div class="col">
          <h1>
            {% block content_title %}

            {% endblock %}
          </h1>
          {% block content %}

          {% endblock %}

      </div>
    </div>



  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Document</title>
  </head>
  <body>
    <h1>Hello {{ n[0] }}</h1>
  </body>
</html>

app/templates/security/login_user.html
{% extends 'base.html' %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}


{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
</form>
{% include "security/_menu.html" %}

{% endblock %}